inherit_from:
- .rubocop_airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 120

AllCops:
  Exclude:
    - 'db/*'
    - 'bin/*'
    - 'bun/bundle'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    
