name: Run tests and Deploy to Heroku

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  run_spec:
    name: Run Rspec Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
          aws-region: ap-northeast-1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.20.0"
      - name: pg gem install
        run: |
          sudo apt-get update; sudo apt-get install libpq-dev
      - name: yarn install
        run: |
          yarn install --check-files
      - name: gem install
        run: |
          gem install bundler -v 1.17.3
      - name: bundler install
        run: |
          bundle check || bundle install --path vendor/bundle --jobs 4 --retry 3
      - name: webpacker install
        run: |
          rm -rf bin/webpack*
          bin/rails webpacker:install
          bundle exec bin/rails webpacker:compile
      - name: Setup env
        run: |
          echo "RAILS_ENV=test" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
      - name: Exec RSpec
        run: |
          bundle exec rspec --format documentation --force-color --backtrace
      - name: Exec rubocop
        run: |
          bundle exec rubocop --extra-details --display-style-guide --parallel --display-cop-names

  deploy_to_heroku:
    name: Deploy to Heroku
    needs: run_spec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "kensyu-maker"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
