name: Rspec

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      with:
        ruby-version: '3.1.2'

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: check Ruby version
      run: ruby -v

    - name: check directory
      run: |
        pwd
        bundler -v

    - name: sqlite3 install
      run: |
        sudo apt install libsqlite3-dev
        gem install sqlite3 -v '1.4.2' --source 'https://rubygems.org/'
        dpkg -L libsqlite3-dev

    - name: Cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: database setup
      run: |
        bundle exec rails db:create RAILS_ENV=test
        bundle exec rails db:migrate RAILS_ENV=test

    # Rspec実行
    - name: run Rspec
      env:
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      run: bundle exec rspec
